kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mustafar-tiller-binding
  namespace: mustafar
subjects:
- kind: ServiceAccount
  name: vader
  namespace: mustafar
roleRef:
  kind: Role
  name: mustafar-tiller-manager
  apiGroup: rbac.authorization.k8s.io
